# Generated by Django 5.2.1 on 2025-06-15 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('primary_color', models.CharField(default='#e40521', max_length=7)),
                ('secondary_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('hero_image', models.ImageField(upload_to='bikes/')),
                ('features_image', models.ImageField(upload_to='bikes/')),
                ('design_image', models.ImageField(upload_to='bikes/')),
                ('engine_image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('features_title', models.CharField(blank=True, max_length=200)),
                ('features_description', models.TextField()),
                ('design_title', models.CharField(blank=True, max_length=200)),
                ('design_description', models.TextField()),
                ('engine_type', models.CharField(max_length=200)),
                ('displacement', models.CharField(max_length=50)),
                ('bore_stroke', models.CharField(max_length=50)),
                ('compression_ratio', models.CharField(max_length=50)),
                ('max_power', models.CharField(max_length=50)),
                ('max_torque', models.CharField(max_length=50)),
                ('fuel_system', models.CharField(max_length=100)),
                ('fuel_tank_capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
        ),
    ]
