# Generated by Django 5.2.1 on 2025-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='chassis_image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='clutch_type',
            field=models.CharField(default='Wet, multiplate clutch', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='dimensions',
            field=models.CharField(default='2,110 mm × 750 mm × 1,150 mm', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='dimensions_image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='frame_type',
            field=models.CharField(default='Diamond', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='front_brake',
            field=models.CharField(default='310 mm dual disc with 2-piston calipers, ABS', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='front_suspension',
            field=models.CharField(default='Showa 41 mm SFF-BP USD fork', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='front_tyre',
            field=models.CharField(default='120/70ZR17M/C (58W)', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='ground_clearance',
            field=models.CharField(default='130 mm', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='kerb_weight',
            field=models.CharField(default='207 kg', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='rear_brake',
            field=models.CharField(default='240 mm single disc with single-piston caliper, ABS', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='rear_suspension',
            field=models.CharField(default='Monoshock damper, 10-step preload adjustable', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='rear_tyre',
            field=models.CharField(default='180/55ZR17M/C (73W)', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='seat_height',
            field=models.CharField(default='810 mm', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='transmission_image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='transmission_type',
            field=models.CharField(default='6-speed', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='wheelbase',
            field=models.CharField(default='1,450 mm', max_length=50),
        ),
    ]
